### ISSUE TITLE
Bennennung der Räume

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/dojo-dungeon#56]
Ich habe heute versucht, die Doku und den Code zu matchen und zu verstehen, was die einzelnen Räume machen. 

Die Namensgebung finde ich ziemlich ... 

Eigentlich sollten die Räume richtige Namen bekommen, nicht 1, 2, 3 ... 

Und wenn schon Nummern, dann bitte das Level da mit reinkodieren. In der Doku schreibt ihr ja auch "Level 1: Raum 2".

**Comment by tgrothe** [comment]
Eine Möglichkeit wäre:

L1_R1_Monster_1
L1_R2_Fehler_Syntax
L1_R3_Fragen_Lambda

L2_R1_Monster_2
L2_R2_Monster_Implement_1
L2_R3_Fehler_Refactoring

L3_R1_Fragen_Schriftrollen
L3_R2_Fehler_Quader
L3_R3_Fragen_RegExes

L4_R1_Monster_3
L4_R2_Fragen_Pattern
L4_R3_Monster_Implement_2

@Denniso3 @cagix ist das ok?

**Comment by Denniso3** [comment]
@tgrothe Ja, ich finde das kann man so übernehmen.

**Comment by cagix** [comment]
Unterstriche sind in Java immer so eine Sache. Vielleicht "L4R2Monster"? Oder doch den Räumen richtige Namen geben? Aber letztlich ist das auch egal, ein "L4_R2_Monster" erfüllt seinen Zweck besser als "Raum11"

**Comment by tgrothe** [comment]
> Unterstriche sind in Java immer so eine Sache. Vielleicht "L4R2Monster"? Oder doch den Räumen richtige Namen geben? Aber letztlich ist das auch egal, ein "L4_R2_Monster" erfüllt seinen Zweck besser als "Raum11"

danke, das denke ich eigentlich auch ...

dürfen wir die beschreibung der einzelnen klassen/räume auf deutsch beschreiben?

**Comment by cagix** [comment]
> dürfen wir die beschreibung der einzelnen klassen/räume auf deutsch beschreiben?

das wäre immer noch besser als keine beschreibung :)
