### ISSUE TITLE
Fehlerhafte Klasse

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/dojo-dungeon#58]
Was genau ist an der "Fehlerhafte Klasse" kaputt? Auf den ersten Blick fehlen da Includes. Aber sonst scheint sogar die Funktionalität zu stimmen, also zum jeweiligen Kommentar zu passen? Soll das die Lösung sein oder hab ich grad was auf den Augen?

Edit: Und was hat es mit der schrägen Namensgebung auf sich? `testExpectedOutput7` und `testExpectedOutput8`? Wo sind 1, 2, 3, 4, 5, 6?

**Comment by tgrothe** [comment]
Die "fehlerhafte Klasse" soll ja nur kleinere Syntax- und Semantikfehler enthalten, die der Spieler im Rahmen eines Refactoring während des Spiels verbessern soll. Es wäre deshalb seltsam, die Implementierungen komplett wegzulassen.

`testExpectedOutput7` und `8`, weil unter anderem "7" und "8" von den Methoden als Ausgabe erwartet wird. Aber das könnte verwirrlich bzw. doppelt sein, stimmt.

Und die Aufgabenstellungen in den jeweiligem Raum sollen ja dem Spieler durch die Dialoge der Entities erzählt werden.

**Comment by cagix** [comment]
> Die "fehlerhafte Klasse" soll ja nur kleinere Syntax- und Semantikfehler enthalten, die der Spieler im Rahmen eines Refactoring während des Spiels verbessern soll. Es wäre deshalb seltsam, die Implementierungen komplett wegzulassen.

den satz verstehe ich grad inhaltlich nicht.

wenn ich mir die vorgabe-datei anschaue: ich sehe auf den ersten blick keine probleme bis auf den fehlenden import/include. auch die in den javadocs erwähnte ausgabe scheint mir auf den ersten blick berechnet zu werden?



> 
> `testExpectedOutput7` und `8`, weil unter anderem "7" und "8" von den Methoden als Ausgabe erwartet wird. Aber das könnte verwirrlich bzw. doppelt sein, stimmt.
> 
> Und die Aufgabenstellungen in den jeweiligem Raum sollen ja dem Spieler durch die Dialoge der Entities erzählt werden.

ja, aber auch der code sollte eine geschichte erzählen und nicht nur "f1", "f2" und so heissen. ich finde das ziemlich schwierig und unübersichtlich.

**Comment by tgrothe** [comment]
@cagix welche methodennamen würdest du vorschlagen? (foo, bar, baz? ;)) und sollte es noch zusätzliche oder andere kaputte dinge zum bearbeiten in dieser klasse geben?
