### ISSUE TITLE
Reihenfolge

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/dojo-dungeon#60]
## Level 1: "Der Vergessene Wald"

- R1: Schlüssel (Monster)
- R2: Java-Datei mit Fehlern
- R3: Bosskampf: **RegExp** => **Woche 10 (KW25)**

## Level 2: "Tempel der verlorenen Geheimnisse"

- R4: Saphir (Monster)
- R5: Monster programmieren (Vorgabe: Rumpfstruktur)
- R6: Bosskampf: **Refactoring** => **Woche 9 (KW24)**

## Level 3: "Kerker des Grauens"

- R7: Schriftrollen in Truhen ablegen (Pattern, Development Principles)
- R8: Java-Datei mit Fehlern
- R9: Bosskampf: UML (**Visitor, Observer**) => **Woche 11 (KW26)**

## Level 4: "Die Vulkanhöhle"

- R10: (Monster)
- R11: NPC mit Fragen zu **Lambda-Ausdrücken** (MC-Frage) => **Woche 4 (KW19)**
- R12: Bosskampf: Verhalten implementieren

**Comment by tgrothe** [comment]
Neu:

```plain
R1 Schlüssel (Monster)
R2 Java-Datei mit Syntax-Fehlern
R3 NPC / Lambda-Fragen (MC)   (ehemals R11)

R4 Saphir (Monster)
R5 Monster programmieren (Vorgabe: Rumpf)
R6 Bosskamp: Refactoring      (passt)

R7 Schriftrollen in Truhen ablegen
R8 Java-Datei mit Fehlern
R9 Bosskampf: RegEx           (ehemals R3)

R10 Monster schlagen
R11 Bosskampf: UML            (ehemals R9)
R12 Bosskampf: Verhalten (in-place)
```

Schritte:

```plain
r3       -> r3_temp
r9       -> r9_temp
r11      -> r11_temp

r3_temp  -> r9
r9_temp  -> r11
r11_temp -> r3
```

Danach sollten die Räume umbenannt werden und jede Klasse sollte eine kurze Beschreibung erhalten, was in dieser (am Anfang) zu tun ist. @Denniso3

**Comment by cagix** [comment]
reihenfolge sollte pasen. 👌
